### PR TITLE
Direct capture from DVRescue Mac CLI

### PR DESCRIPTION
**Pull request by JeromeMartinez**
`dvrescue device://0` will capture from the 1st device.
This PR contains also a function `RewindToTimeCode()`, but not yet used (need to find a good algorithm for deciding when to go back and dump again).

### CODE REVIEW

**Comment by dericed** [comment]
HI @JeromeMartinez to help with testing can you provide a dmg of this PR. cc @ElderOrb

**Comment by dericed** [comment]
unclear how to test this. With latest dmg, the suggested command doesn't work for me.
```
% avfctl -list_devices
2021-08-18 15:54:53.551 avfctl[3992:68267] Devices:
2021-08-18 15:54:53.552 avfctl[3992:68267] [0] DV-VCR (Sony HVR-M15AU)

% dvrescue device://0
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210817</version>
		<library version="21.03">MediaInfoLib</library>
	</creator>
</dvrescue>
```

**Comment by g-maxime** [comment]
20210818 is built from the main branch, please tries https://mediaarea.net/download/snapshots/binary/dvrescue/20210816/dvrescue_CLI_0.20.11.20210816_Mac.dmg

**Comment by dericed** [comment]
Thx @g-maxime, when I run `dvrescue device://0` the attached device plays and it hangs at
```
% dvrescue device://0
2021-08-18 18:12:01.722 dvrescue[58650:248222] Frame dropped.
```

When I stop the playback (via the deck), then dvrescue stops with:

```
% dvrescue device://0
2021-08-18 18:12:01.722 dvrescue[58650:248222] Frame dropped.
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210816</version>
		<library version="21.03">MediaInfoLib</library>
	</creator>
	<media error="not DV"/>
</dvrescue>
```

Tried with `dvrescue device://0 -m file.dv` but I got no output file from any instance, but it does make the deck play.

**Comment by g-maxime** [comment]
@dericed Does it work with avfctl from the same snapshot?

**Comment by dericed** [comment]
blerg, maybe user error, `dvrescue device://0` is working at the moment.

```
% dvrescue --version
DVRescue v.0.20.11.20210816 (MediaInfoLib v.21.03) by MIPoPS.
davidrice@iMac homebrew-amiaos % dvrescue device://0
2021-08-20 17:32:38.536 dvrescue[11413:1289793] Frame dropped.
^C 522 00:00:12;09 00:00:12;09 

% dvrescue device://0 -m test.dv
DVRescue v.0.20.11.20210816 (MediaInfoLib v.21.03) by MIPoPS
^C  56 00:00:25;04 00:00:25;04 

% ls -l test.dv
-rw-r--r--  1 davidrice  staff  6717440 Aug 20 17:33 test.dv
```

Issue of output not being frame aligned is still there, but capture is ok.

**Comment by dericed** [comment]
maybe in the prior test i was on a blank part of the tape

**Comment by dericed** [comment]
please rebase.

**Pull request merged**
