### PR TITLE
[WIP] Capture chart

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by dericed** [comment]
Looks good. For reference, here's an image:

image

Comments:
- can you reduce the height, 50% of the current height would be fine.
- In my sample, the values vary slight but generally BlockErrors=1350 (column 16) and 
BlockErrors_Even (column 17) equals 675. The plot should show both `(BlockErrors_Even)` and `((BlockErrors-BlockErrors_Even) * -1)` (or however it was done on the analysis graph, so odd and even are plotted in different vertical directions from zero.
- For the graph, can you keep a rolling variable `y` of the count of frames in the last `x` frames where `BlockErrors!=0` (where `x` is the number of frames plotted in the graph) and a variable `z` of the total number of frames with errors. Then make a tooltip on the graph that says `Of the %total_frames received, %z contain errors. In the last %x frames, %y contain errors.`

@libbyhopfauf, @privatezero, comments on the image?

**Comment by libbyhopfauf** [comment]
I think this looks great! I agree that a rolling count of the number of errors would be really helpful for determining if maybe you should stop the capture prematurely and clean your deck or check for other issues.

**Comment by privatezero** [comment]
+1 to the rolling count of total errors

**Comment by dericed** [comment]
Sorry, @elderorb merge conflicts after latest merged. 0:)

**Comment by dericed** [comment]
btw TransferPage.qml was renamed CapturePage.qml

**Comment by dericed** [comment]
- If not in play or record, simply plot a vertical gray bar (concealment is expected in shuttle mode) and do not count those frames.
- Reset graph when start record or switching from record to anything but stop.
- Please review the width of the plotted value, the width should be the distance from one tick to the next, currently there's space between them occasionally (see images).
image
image
image

Let's change the tooltip:
if the current recording has less than 9000 frames then:
`Of the X frames received, Y contain error concealment.`
if >=9000 frames then:
`Of the X frames received, Y contain error concealment (Z within the last 9000 frames).`
extra credit: adjust pluralization of 'contain' to contains when Y<2.

**Comment by dericed** [comment]
Much improved, thanks. As I'm reviewing I'm wondering if it's worth bringing over more of the analysis graph (i.e. the zoom in/out/100%, horiz scroll bar, and frame,N tick labels.

image

vs

Screen Recording 2022-10-16 at 8 55 07 PM
 @libbyhopfauf, thoughts?

**Comment by libbyhopfauf** [comment]
I think just having the audio and video errors running is enough for capture, just so you know if things are going really poorly and should consider stopping to clean your deck or see if there's something else going wrong.

**Comment by dericed** [comment]
@libbyhopfauf, will merge, so this is usable. If you have recommendations for labelling or context, we can start a new issue.

**Pull request merged**
