### PR TITLE
add cc filter

### PR DESCRIPTION
**Pull request by ElderOrb**
windows refuse to work

### CODE REVIEW

**Comment by dericed** [comment]
I get a playback error with this scenario:
1. open a file is sidecar scc (like the Demo one) and play with with cc enabled
2. add a second file with no scc. In the player the cc button will be off, and unresponsive, but the player file tries to use the subtitles filter and gets

```
[2023:12:10 15:57:01 -05:00] [warning] [thread 892416] Could not parse filter desc: "subtitles=" -22
[2023:12:10 15:57:01 -05:00] [warning] [thread 892416] FilterError : "Could not create filters: Invalid argument"
```

Can you add a check to make sure the subtitle file exists before putting an empty variable in the filter? And make sure that the player handles toggles between files with and without scc.

**Comment by dericed** [comment]
and please remove the `F#` part altogether. I realize that the frame number is not in context to the file but the last selected filterchain

**Comment by dericed** [comment]
The prior comments have been addressed.
I'm testing with `Demo_DV_720x480_CC.mov`. I removed all sidecar removes (so there's no xml or scc). Then I drag the file into analysis view. Unfortunately, the analysis never starts. I would hope that the xml and scc would generate and then the cc button would activate.

**Comment by dericed** [comment]
also Demo_DV_720x480_CC.mov.dvrescue.scc works but not Demo_DV_720x480_CC.scc or Demo_DV_720x480_CC.mov.scc or Demo_DV_720x480_CC[*].scc

**Comment by ElderOrb** [comment]
> I'm testing with `Demo_DV_720x480_CC.mov`. I removed all sidecar removes (so there's no xml or scc). Then I drag the file into analysis view. Unfortunately, the analysis never starts. I would hope that the xml and scc would generate and then the cc button would activate.

Hmm, could it be the case there is something wrong with permissions? Works on my env / Windows

**Comment by ElderOrb** [comment]
> also Demo_DV_720x480_CC.mov.dvrescue.scc works but not Demo_DV_720x480_CC.scc or Demo_DV_720x480_CC.mov.scc or Demo_DV_720x480_CC[*].scc

Where can non-dvrescue.scc come from?

**Comment by dericed** [comment]
with the cli, the user can pick the name so it could be uncontrolled, but hopefully the file starts the same but has the scc extension. I'd like to match the behavior of other players in finding related subtitle files.

**Comment by ElderOrb** [comment]
> with the cli, the user can pick the name so it could be uncontrolled, but hopefully the file starts the same but has the scc extension. I'd like to match the behavior of other players in finding related subtitle files.

done, although UI will run 'dvrescue -y file.dv -x file.dv.dvrescue.xml -c file.dv.dvrescue.scc' thus resulting dvrescue.scc

**Pull request merged**
