### PR TITLE
Decklink simulator

### PR DESCRIPTION
**Pull request by g-maxime**

### CODE REVIEW

**Comment by g-maxime** [comment]
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20240306/
@dericed Please test the capture from decklink hardware and the XML output again with this snapshot.

**Comment by dericed** [comment]
I tested both 20240301 and 20240306 and they behaved the same, but I have a broken video card, so not getting vitc timecode here and in both versions the decklink capture stopped after 13-15 frames. I'll retest on my working video card at home.

**Comment by g-maxime** [comment]
New snapshot with fixed memory corruption: https://mediaarea.net/download/snapshots/binary/dvrescue/20240318-2/

**Comment by dericed** [comment]
Testing and the xml from a decklink transfer looks good. But the xsd validation fails for missing the stop and source elements and the size attribute on frames. Please add an xsd update.

Any comments @ElderOrb? Otherwise I'd merge if the CI tests were resolved.

**Pull request merged**
