### PR TITLE
PTS rounding digit count is tweakable

### LINKED ISSUE #47: report pts with 10^-5 of a second precision
For instance, dvrescue reports pts of a frame starting at `00:00:02.169`; however to cut up to but not including that frame in ffmpeg the presentation time to end at would be `00:00:02.16883`.

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix #47.

### CODE REVIEW

**Comment by dericed** [comment]
My bad! I was using a truncated display of pts values from ffmpeg's showinfo filter.  I actually need 10^-6 precision, as shown with `ffprobe test.dv -show_frames -of flat -show_entries frame=pkt_pts_time`

**Comment by JeromeMartinez** [comment]
Easy to change :), [this build](https://mediaarea.net/download/snapshots/binary/dvrescue/20200407/) is with 10^-6 precision.

**Comment by dericed** [comment]
Closing, as I ended up working around the option in a cleaner way but using the -copyts ffmpeg option and adjusting how start and end times are handled. Thanks.

**Comment by dericed** [comment]
Is https://github.com/mipops/dvrescue/pull/48/commits/ba80e5138d9b15bcbf7837794201ce5f79487b79 still worthwhile if the following commit isn't used?

**Comment by JeromeMartinez** [comment]
> Is ba80e51 still worthwhile if the following commit isn't used?

I would like to keep it as it has some fixes for corner cases and easier to maintain.
PR modified accordingly.

**Pull request merged**
