### PR TITLE
GUI: Rework output file dialog

### PR DESCRIPTION
**Pull request by g-maxime**
+ Use a custom dialog with folder picker to get write permission for multiples files on macOS

Capture d’écran 2022-08-31 à 18 19 56

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
@dericed @libbyhopfauf @privatezero the macOS sandbox does not permit to select a file for write then additionally write side car files (side car files are not authorized to be written), so we propose this method for having the authorization on the folder.
[This snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/20220831/dvrescue_CLI_0.21.11.20220831_Mac.dmg) has the patch.

**Comment by dericed** [comment]
When I build this I get:
```
$ ./dvrescue/dvrescue.app/Contents/MacOS/dvrescue 
appDirPath:  "/Users/archivesx/Documents/GitHub/dvrescue/Source/GUI/dvrescue/build/dvrescue/dvrescue.app/Contents/MacOS"
PATH:  "/Users/archivesx/Documents/GitHub/dvrescue/Source/GUI/dvrescue/build/dvrescue/dvrescue.app/Contents/MacOS/../Helpers:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin"
qt.qpa.fonts: Populating font family aliases took 410 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
QQmlApplicationEngine failed to load component
qrc:/main.qml:257:5: Type SpecifyPathDialog unavailable
qrc:/SpecifyPathDialog.qml:4:1: module "QtQuick.Controls" version 1.2 is not installed
category:  qt.qpa.plugin false
....
```


using
```
$ qmake -v
QMake version 3.1
Using Qt version 6.3.1 in /usr/local/lib
```

**Comment by dericed** [comment]
btw the snapshot link is to cli, the gui one for that release is at https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20220831/dvrescue_GUI_0.21.11.20220831_Mac.dmg. I tested this and it works ok. I think the capture directory should be remembered from one capture to next, but here the filename is too. I suggest to clear the filename whenever this dialog appears. Oddly I tried to do two captures at same time and the 2nd one was ok, but the first capture was only a single frame although the xml documented a few thousand frames.

**Comment by dericed** [comment]
the dialog also allows invalid output names which causes the capture to hang. For instance I tried `test.4dv` and it hangs. The end of the filename should be restricted to '.dv'.

**Comment by g-maxime** [comment]
> the dialog also allows invalid output names which causes the capture to hang. For instance I tried `test.4dv` and it hangs. The end of the filename should be restricted to '.dv'.

Ok, I didn't know about this limitation.
PR updated : append .dv to the filename if not present

**Pull request merged**
