### PR TITLE
Absolute track number in XML report

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by dericed** [comment]
Am testing this on https://makeinstallnotwar.org/video/Demo_DV_720x480_CC.mov.

output is
```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210215</version>
	</creator>
	<media ref="Demo_DV_720x480_CC.mov" format="QuickTime" size="303383148">
		<frames count="2400" pts="00:00:00.000000" end_pts="00:01:20.080000" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" captions="y">
			<frame n="0" pos="199768" pts="00:00:00.000000" abst="1019790" tc="00:37:46:06" arb="0"/>
			<frame n="2384" pos="301463148" pts="00:01:19.546133" abst_r="1" abst_nc="1" tc="00:00:00;00" tc_nc="1" arb="0" arb_nc="1" no_pack_aud="1"/>
			<frame n="2399" pos="303263148" pts="00:01:20.046633" abst_r="1" abst_nc="1" tc="00:00:00;00" tc_r="1" arb="0" arb_nc="1" no_pack_aud="1"/>
		</frames>
	</media>
</dvrescue>
```

I suggest to state `@abst` on all `<frame>` elements. Here I only see it on the first one of the `<frames>`.

Next test, I extract the dv from the mov with `ffmpeg -i Demo_DV_720x480_CC.mov -map 0:v -c copy -f rawvideo Demo_DV_720x480_CC.dv`.

```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210215</version>
	</creator>
	<media ref="Demo_DV_720x480_CC.dv" format="DV" size="288000000">
		<frames count="2400" pts="00:00:00.000000" end_pts="00:01:20.080000" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" captions="y">
			<frame n="0" pos="0" pts="00:00:00.000000" abst="1019799" tc="00:37:46:06" arb="0"/>
			<frame n="2384" pos="286080000" pts="00:01:19.546133" abst_r="1" abst_nc="1" tc="00:00:00;00" tc_nc="1" arb="0" arb_nc="1" no_pack_aud="1"/>
			<frame n="2399" pos="287880000" pts="00:01:20.046633" abst_r="1" abst_nc="1" tc="00:00:00;00" tc_r="1" arb="0" arb_nc="1" no_pack_aud="1"/>
		</frames>
	</media>
</dvrescue>
```

First `@abst` value of the mov is `1019790` and first of the dv extracted is `1019799`. This is unexpected since it should be the same frame.

**Comment by dericed** [comment]
Please bump xsd version to 1.2 since lack of abst implies it is not in the stream, which is a semantic change from 1.1. I'll prep a PR for the XSD.

**Comment by dericed** [comment]
Testing with:

[BAVC1010004_DSR20_100014_start757800001_for8400000.dv.zip](https://github.com/mipops/dvrescue/files/5999182/BAVC1010004_DSR20_100014_start757800001_for8400000.dv.zip)

dvrescue -v 0 BAVC1010004_DSR20_100014_start757800001_for8400000.dv | xml sel -N "d=https://mediaarea.net/dvrescue" -t -m "/d:dvrescue/d:media/d:frames/d:frame" -v @n -o " " -v @abst -o " " -v @abst_nc  -o " " -v @abst_r -n 
```
0 63216  
15  1 1
24  1 1
25 65535  
68 63890 1 
69 63900 
```

The output is `@n @abst @abst_nc @abst_r` so frame 15 and 24 show a jump and repeat but no abst. Frame 25 has an out of order value (is there another correct abst in the frame, or a more frequently occuring value?).

**Comment by dericed** [comment]
btw `O_O.dv` is an example of DV50 from tape. Seems to increment by 20 rather than 10 (makes sense). PAL DV25 increments by 12, so the incrementation just seems to be by 1 per DIF sequence.

**Comment by JeromeMartinez** [comment]
Algo tweaked in order to get less "false-positive":
- if abst is not in the first 12 KB of the frame, adapt the value by offset/12K
- Non-consecutive only if value is > last one + 2x the expected gap (avoid to flag Non-consecutive if e.g. gaps of 15, a missing frame would be minimum 20)

blank field flag not yet handled, useful handling of this flag needs more discussion.

**Comment by JeromeMartinez** [comment]
2nd commit is a bit out of scope but as it is small and to be included in 1.2 XSD, I put it in this PR.
MediaInfo lib API is not changed, only the XML output is changed, in order to avoid API break only for a renaming.

**Comment by dericed** [comment]
nudge on https://github.com/mipops/dvrescue/pull/242/commits/d57c165b2db94564adba5cc1d576ed72b82b5b19#diff-d5fdb80d7479ac3f326bea1bf64f8d610ac596f90f0639f8eb9d93881b86cd17R108

**Comment by dericed** [comment]
Getting some 0x7FFFFc. Please check. 
[DVC00010001_9962400000.dv.zip](https://github.com/mipops/dvrescue/files/6055150/DVC00010001_9962400000.dv.zip)
[DVC00010001_165960000.dv.zip](https://github.com/mipops/dvrescue/files/6055151/DVC00010001_165960000.dv.zip)

**Comment by JeromeMartinez** [comment]
Very weird, it seems like a negative abst, for example DVC00010001_165960000.dv starting the 2nd frame (frame 1):
- each dseq has an incremented value, 10x
- distance is only 5! (frame 1 from -4 to 5, frame 2 from 1 to 10, frame 3 from 6 to 15)
but not really important there.

If I discard 0x7FFFFC+ values, frame 1 would have no abst and would be considered as a part of frame 0 related group (abst_nc at frame 2).
If I handle 0x7FFFFC+ values as negative abst, frame 1 would have a negative abst and would be considered as a part of frame 2+ related group (abst_nc at frame 1, which makes more sense IMO, as frame 0 has a totally different abst and frame 1+ are in sequential order).

Maybe it would make sense to handle such weird abst as negative abst in order to catch well this kind of crazy abst.

**Comment by dericed** [comment]
I agree in support this odd negative abst, but only to the negative amount of the greater frame to frame abst difference.

**Comment by dericed** [comment]
[DVC00978_0_00_00_08_first5.dv.zip](https://github.com/mipops/dvrescue/files/6071700/DVC00978_0_00_00_08_first5.dv.zip)

Another sample with negative abst possibilities.

**Comment by JeromeMartinez** [comment]
> DVC00978_0_00_00_08_first5.dv.zip

buggy abst in frame 83 & 84 without valid abst in the same frame (sometime 8357224 in the whole dseq, sometimes 8357224 and 1392 in the same dseq etc).
frame 85 has a similar pattern but with more valid abst in the same frame which is used so you don't see it in the report. but abst is (when buggy values removed) 1396, so as if 1 frame is missing (or is the impact of frame 82 being a repeated frame). I guess that read of the tape was very difficult between frames 82 and frame 84.
I'll filter such buggy abst by checking that the abst is coherent in the frame (sequential order in all dseq of a frame).

Would it worth it to have an indicator of incoherent abst and show the frame in the report in that case?

**Comment by dericed** [comment]
> Would it worth it to have an indicator of incoherent abst and show the frame in the report in that case?

I'm uncertain. I worry that reporting abst incoherency would result in a lot of spamming. Perhaps we can consider it later, when considering *_inc or *_mix attributes, but let's move that consideration to a separate PR.

**Comment by JeromeMartinez** [comment]
[New build](https://mediaarea.net/download/snapshots/binary/dvrescue/20210308/), using https://github.com/MediaArea/MediaInfoLib/pull/1377

Previous version was having some false positives with super buggy files.
Trying to avoid them.

- Handle Absolute track number with steps of 5 (current frame start value in the middle of the values from previous frames)
- Handle Absolute track number with steps of 15 (2 then 1 pattern for each Dseq)
- Handle Absolute track number with "random" values in the up to 40 places found; this is [heuristic](https://en.wikipedia.org/wiki/Heuristic)
- - Handle negative Absolute track number

**Pull request merged**
