### PR TITLE
HTML display for dvplay output

### PR DESCRIPTION
**Pull request by ablwr**
See below for latest screenshot.

Opening a PR for an easy-linkable `diff` and public place to drop the screenshot.

Working on an easy-to-read display for the output of `dvplay -x`.

There are a lot of variables still at play that I'm making assumptions about. One of the smaller ones is the exported filenames by dvplay -- so I went the easiest route and adjusted dvplay to spit out non-ideal jpg names with `:` in them.

Right now, dvplay is creating jpgs for all of the error frames but not creating ones for the ins/outs, is that intended? You can see in the image below. I could have the display hide the first and last, or dvplay can cut jpgs for the first/last.

Screenshot_2019-12-17 Screenshot

### CODE REVIEW

**Comment by dericed** [comment]
adding first and last frames seems fine, though the report should note if a frame is an error or not. If an error then we could summary the error with the data in dseq. Do you have a sample with >1 <frames> element and errors?

**Comment by ablwr** [comment]
> though the report should note if a frame is an error or not

Will do!

> Do you have a sample with >1 element and errors?

What do you mean by `element`?

**Comment by dericed** [comment]
Oops, meant ">1 \<frames\> element" but the xml node was dropped (now escaped).

**Comment by ablwr** [comment]
Ah! More than one frame would just repeat the entire section, like this (sorry it's only ins/outs, no pix)

Screenshot_2019-12-17 Screenshot(1)

**Comment by ablwr** [comment]
As you can see from my output, I should update my version of `dvrescue` to the latest though!

**Comment by ablwr** [comment]
Should we only display frames that include a `dseq/sta`?

**Comment by ablwr** [comment]
Screenshot_2019-12-18 Screenshot

**Comment by ablwr** [comment]
I will have to review this again, but I think I am parsing/displaying all the data I'm currently aware of, given what DVRescue is giving me. 

Screenshot_2019-12-31 Screenshot

**Comment by ablwr** [comment]
Other than the display, this branch also modifies `dvplay` to look for a font on Ubuntu machines and changes the pattern for creating image files (basically, removes the filename, which is hard to grab using XSLT1.0. If the filename should definitely be structured this way, maybe we can consider a filename attribute instead of the full path).

**Comment by ablwr** [comment]
This is tentatively ready for review... at least as a first draft.

Some questions:

- Are there other planned changes to the XML output that I should anticipate?
- Should I plan for presentation of a gif?
- Should all frames be shown, or only frames that include dseq elements?
- `sta`'s `t` attribute is defined in the XSD but I saw a few t values of 13. Since that wasn't documented in the xsd, it has no value -- but should it (is this WIP deciphering)?
- I note when something is non-consecutive or repeating. Should I do the converse -- make note of when non-repeating or consecutive, or should that just be assumed as the default/implicit?
- `rec_start` and `rec_end` are boolean so I am checking for their existence at all right now, but perhaps for an explicit =1 is better. This might need to change, but wondering if there's any changed plans for these two elements? I'd like to better define the definition in the XSD.

**Comment by dericed** [comment]
very late review. @ablwr I rebased this on master and added some commits to sync the filenames mostly and also to apply the transform after the jpgs are made. Rather than handling an install of display.xsl I included it as a here document that is written out to a temp directory to be used. If all good with you, let's merge (pending resolve of github actions) and then can continue to work on this from there.

**Comment by ablwr** [comment]
Agreed!!

**Pull request merged**
