### PR TITLE
[WIP] Capture visualization

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by dericed** [comment]
can you replace colorbars.jpg with this image
nosignal
.

**Comment by dericed** [comment]
The capture command is:
`dvrescue device://$DEV -m $OUTPUTFILE`

please add in the xml and scc outputs:

`-x "$XML" -c "$SCC" --cc-format scc`

```
XML="${OUTPUTFILE%.*}.dv.dvrescue.xml"
SCC="${OUTPUTFILE%.*}.scc"
```

So full command is
`dvrescue device://$DEV -x "$XML" -c "$SCC" --cc-format scc -m $OUTPUTFILE`

and outputs should be (note that the scc will only be written if the input includes caption data):
```
name.dv
name.dv.dvrescue.xml
name.scc
```

**Comment by dericed** [comment]
Can you adjust the play command from `avfctl -dev x -cmd play` to something similiar to the capture command but without writing the file. That would also the user to see the file and associated metadata during playback.

**Comment by dericed** [comment]
In dialog block to save the file, when i enter the first character of the output filename, then the `.dv` extension is auto added and my cursor is now after the `.dv`, so to enter other characters I have to backspace or reset the cursor. I also note that once the capture is started then the user doesn't have a clue to correlate the player to the output file.

I suggest to divide it up by adding a panel to the right of the player with: small text entry for 'Tape ID` and another for Output Directory. $tapeid can then be the root of $tapeid.dv, $tapeid.dv.dvrescue.xml, and $tapeid.scc.

**Comment by dericed** [comment]
In to-be-added right panel on player. Can we also add a capture option with three choices:
1. Capture from current position
2. Rewind tape and capture from beginning
3. Repack tape and capture from beginning

For option 1, the current approach works, if option 2, then proceed the capture with this command and wait until it's finished `avfctl -foreground -dev 0 -cmd rew`, if option 3, then `avfctl -foreground -dev 0 -cmd ff ; avfctl -foreground -dev 0 -cmd rew`.

**Comment by ElderOrb** [comment]
> can you replace colorbars.jpg with this image nosignal .

Does it even need to be an image? I see only black background with a white static text.

**Comment by ElderOrb** [comment]
> Can you adjust the play command from `avfctl -dev x -cmd play` to something similiar to the capture command but without writing the file. That would also the user to see the file and associated metadata during playback.

Does it need visualization or just metadata?

**Comment by dericed** [comment]
Both visualization and metadata. 
the image is for when a deck is there but no video is playing.

**Comment by dericed** [comment]
Also noting that capture stops at 2147465536 bytes, a little below 2GB

**Pull request merged**
