### PR TITLE
Xsd update abst

### PR DESCRIPTION
**Pull request by dericed**
to merge before https://github.com/mipops/dvrescue/pull/242 and document its xml changes.

### CODE REVIEW

**Review by JeromeMartinez — CHANGES_REQUESTED** [review]
blank field flag is not yet implemented and we are currently planning to change the way it is handled, better to remove it from XSD for the moment.

**Comment by dericed** [comment]
addresses the xsd part of https://github.com/mipops/dvrescue/issues/230

**Review by JeromeMartinez — APPROVED** [review]

**Comment by dericed** [comment]
added library info. Will merge after checks.

**Comment by dericed** [comment]
Resolved in https://github.com/mipops/dvrescue/pull/242, excepting `@bf` for later investigation.

**Pull request merged**
