### PR TITLE
QtAV => QtAVPlayer

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by dericed** [comment]
So far, so good. @JeromeMartinez, do you want to review before merge?

**Comment by JeromeMartinez** [comment]
I let @g-maxime try to build on our build farm.

**Comment by dericed** [comment]
thx @ElderOrb and thx @valbok!!! :-D

**Comment by JeromeMartinez** [comment]
@dericed please test [this snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20210830/). Should be digitally signed etc.

**Comment by JeromeMartinez** [comment]
While building on Linux with the Qt libs provided by the distro, there is a compilation error due to the usage of a private include:

```
dvrescue/Source/GUI/dvrescue/dvrescue-QtAVPlayer/src/QtAVPlayer/qtavplayerglobal_p.h:22:10: fatal error: QtGui/private/qtguiglobal_p.h: No such file or directory
```

private includes are not intended to be used outside of Qt itself, and are not provided by the distros + are not stable (no compatibility between versions). It would be a lot better to avoid that.

**Comment by valbok** [comment]
Removed https://github.com/valbok/QtAVPlayer/pull/127

**Pull request merged**
