### PR TITLE
Add inverse design logo for dark backgrounds

### PR DESCRIPTION
**Pull request by ablwr**
Adding in this logo (Thank you @libbyhopfauf) for use in the GUI -- better for the darker background.

cc @ElderOrb

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
We need a unique logo file, independen from the background (which fits with both clear and dark backgrounds), at least for the app icon.

**Comment by ablwr** [comment]
@libbyhopfauf do you think you could come up with a logo with a clear background and using a middle gray tone, so that the logo can work with both dark and light backgrounds?

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf do you think you could come up with a logo with a clear background and using a middle gray tone, so that the logo can work with both dark and light backgrounds?

100% I'll get a few options to you by tomorrow!

**Comment by libbyhopfauf** [comment]
Would one of these work?

DVRescue_gray_option01
DVRescue_gray_option02

**Comment by JeromeMartinez** [comment]
Seems fine with Windows dark mode:
image

**Pull request merged**
