### PR TITLE
Expand Settings panel

### PR DESCRIPTION
**Pull request by ElderOrb**
https://github.com/mipops/dvrescue/issues/565

### CODE REVIEW

**Comment by ElderOrb** [comment]
image

**Comment by dericed** [comment]
@ElderOrb Can you add a shortcut to the SETTINGS tab via the toolbar menu like you did for the about page, `dvrescue > Preferences`?

**Comment by ElderOrb** [comment]
image

**Comment by ElderOrb** [comment]
https://github.com/mipops/dvrescue/issues/505 ^^

**Comment by ElderOrb** [comment]
Rebased on main & resolved conflicts

**Pull request merged**
