### PR TITLE
Handle user interruption (ctrl-c)

### PR DESCRIPTION
**Pull request by g-maxime**
Depends on MediaArea/MediaInfoLib#1622

Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20221123-2/

Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Review by JeromeMartinez — APPROVED** [review]

**Comment by JeromeMartinez** [comment]
In the case of file parsing, the XML is outputted correctly after ctrl-c but there is no tip that the file was partially parsed. @dericed do you wish a XML attribute about partial parsing or fine without it?

**Comment by dericed** [comment]
@JeromeMartinez, an attribute makes sense, maybe `<media><message type='warning'>The file was only evaluated up to $evaluation_offset.<media>`. But if Control-C causes a partial xml output, could we have an interactive command (maybe `q`) to stop the reading when the user wants to stop.

Actually, maybe the stop method is worth logging in the xml:

```
<media ref='file'>
    <command>$original_command_line_request</command>
    <stop method='timeout' secs='10'/> # stopped because the capture timed out at 10 seconds
    <stop method='user' signal='SIGINT'/> <!-- control-c -->
    <stop method='deck' message='Tape ended or the deck was stopped'/>
</media>
```

Thoughts?

**Comment by JeromeMartinez** [comment]
> Actually, maybe the stop method is worth logging in the xml [...] Thoughts?

IMO it is a bit too much, I would do:
- default (no extra info) means be EOF / End or tape
- `<media><stop method='timeout' extra='10'/>`
- `<media><stop method='user' extra='SIGINT'/>` (avoiding too many things in XSD). `size` media attribute would contain the evaluation offset, as it does for time out or tape end.

> <command>$original_command_line_request</command>

Independent.
IMO not so useful, but does not hurt if you wish it.

**Comment by dericed** [comment]
I tested and this works well, thus far the xml matches the dv in terms of the frame count.

**Comment by dericed** [comment]
will merge and move the comment in https://github.com/mipops/dvrescue/pull/650#issuecomment-1329482080 to an issue

**Pull request merged**
