### PR TITLE
Avoid starting a sequence with no audio pack then audio pack

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix https://github.com/mipops/dvrescue/issues/329.

### CODE REVIEW

**Comment by dericed** [comment]
Noted in chat. But two issues shown in https://gist.github.com/dericed/d541e2585defcd11ed6d74a4cf7fdbee.

In line 9 and 12, these `<frames>` share the same end_pts value.

Line 12 has `is "channels="2" no_sourceorcontrol_aud="1"` but I think `is "channels="0" no_sourceorcontrol_aud="1"` would be more accurate.

**Comment by JeromeMartinez** [comment]
>  I think is "channels="0" no_sourceorcontrol_aud="1" would be more accurate.

I prefer to remove the attribute (as well as all other audio related attributes e.g. audio_rate, as they are based on the next frame, outside of the newly created sequence), like if DV without audio.

**Comment by dericed** [comment]
ok with me

**Comment by dericed** [comment]
Am testing again with the 20210820 build and sample at https://github.com/mipops/dvrescue/files/6872785/BAVC1010855_DV000161_take01-002_audio.dv.zip and here is an output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210820</version>
		<library version="21.03">MediaInfoLib</library>
	</creator>
	<media ref="/Users/davidrice/Downloads/BAVC1010855_DV000161_take01-002_audio.dv" format="DV" size="960000">
		<frames count="1" pts="00:00:00.000000" end_pts="00:00:00.033366" size="720x480" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" abst="2792" tc="00:57:02;27" seqn="F" no_pack_vid="1"/>
		</frames>
		<frames count="1" pts="00:00:00.033366" end_pts="00:00:00.066733" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" no_sourceorcontrol_aud="1">
			<frame n="1" pos="120000" pts="00:00:00.033366" abst="12" tc="00:00:00;00" tc_nc="1" seqn="F" no_sourceorcontrol_aud="1"/>
		</frames>
		<frames count="1" pts="00:00:00.066733" end_pts="00:00:00.100100" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3">
			<frame n="2" pos="240000" pts="00:00:00.066733" abst="12" abst_r="1" tc="00:00:00;00" tc_r="1" seqn="F"/>
		</frames>
		<frames count="5" pts="00:00:00.100100" end_pts="00:00:00.266933" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="3" pos="360000" pts="00:00:00.100100" abst="73" abst_nc="1" tc="00:00:00;04" tc_nc="1" seqn="F"/>
			<frame n="4" pos="480000" pts="00:00:00.133466" abst="73" abst_r="1" tc="00:00:00;04" tc_r="1" seqn="F"/>
			<frame n="5" pos="600000" pts="00:00:00.166833" abst="80" tc="00:00:00;08" tc_nc="1" seqn="F"/>
			<frame n="6" pos="720000" pts="00:00:00.200200" abst="100" tc="00:00:00;10" tc_nc="1" seqn="F"/>
			<frame n="7" pos="840000" pts="00:00:00.233566" abst="110" tc="00:00:00;11" seqn="F"/>
		</frames>
	</media>
</dvrescue>
```

A few issue:

- `frames/@no_sourceorcontrol_aud` is not allowed in schema (this attribute is okay at `<frame>` but not here.

- I am interested in frames n=1 and n=2.
- For Frame n=1 we have `audio_rate="48000" channels="2" no_sourceorcontrol_aud="1"`
- For Frame n=2 there are no audio attributes.
- From that I would expect that frame 1 has audio (or maybe not, no audio pack and channel/rate is confusing) and for frame 2 to have no audio, but ffmpeg says the opposite:

```
% ffmpeg -hide_banner -i subfile,,start,120000,end,240000,,:BAVC1010855_DV000161_take01-002_audio.dv 
[dv @ 0x13e829000] Estimating duration from bitrate, this may be inaccurate
Input #0, dv, from 'subfile,,start,120000,end,240000,,:BAVC1010855_DV000161_take01-002_audio.dv':
  Metadata:
    timecode        : 00:00:00;00
  Duration: 00:00:00.03, start: 0.000000, bitrate: 28770 kb/s
  Stream #0:0: Video: dvvideo, yuv411p, 720x480 [SAR 8:9 DAR 4:3], 25000 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
At least one output file must be specified

% ffmpeg -hide_banner -i subfile,,start,240000,end,360000,,:BAVC1010855_DV000161_take01-002_audio.dv 
[dv @ 0x14b030200] Estimating duration from bitrate, this may be inaccurate
Input #0, dv, from 'subfile,,start,240000,end,360000,,:BAVC1010855_DV000161_take01-002_audio.dv':
  Metadata:
    timecode        : 00:00:00;00
  Duration: 00:00:00.03, start: 0.000000, bitrate: 28770 kb/s
  Stream #0:0: Video: dvvideo, yuv411p, 720x480 [SAR 8:9 DAR 4:3], 25000 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.97 tbc
  Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
At least one output file must be specified
```

I looked more closely at the frames and see that ffmpeg sees right as the audio dif blocks in frame 1 are nulled with 0xff filled audio packs, while frame 2 has audio packs.

Is dvrescue off here? Rather than

```xml
<frames count="1" pts="00:00:00.033366" end_pts="00:00:00.066733" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" no_sourceorcontrol_aud="1">
	<frame n="1" pos="120000" pts="00:00:00.033366" abst="12" tc="00:00:00;00" tc_nc="1" seqn="F" no_sourceorcontrol_aud="1"/>
</frames>
<frames count="1" pts="00:00:00.066733" end_pts="00:00:00.100100" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3">
	<frame n="2" pos="240000" pts="00:00:00.066733" abst="12" abst_r="1" tc="00:00:00;00" tc_r="1" seqn="F"/>
</frames>
```

I would expect:
```xml
<frames count="1" pts="00:00:00.033366" end_pts="00:00:00.066733" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3">
	<frame n="1" pos="120000" pts="00:00:00.033366" abst="12" tc="00:00:00;00" tc_nc="1" seqn="F" no_sourceorcontrol_aud="1"/>
</frames>
<frames count="1" pts="00:00:00.066733" end_pts="00:00:00.100100" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
	<frame n="2" pos="240000" pts="00:00:00.066733" abst="12" abst_r="1" tc="00:00:00;00" tc_r="1" seqn="F"/>
</frames>
```

**Comment by dericed** [comment]
Looks good. Should I wait for merge for any related MediaInfoLib work?

**Comment by JeromeMartinez** [comment]
It is in DVRescue only.

**Pull request merged**
