### PR TITLE
Detail the non-continuity in rdt_nc and tc_nc

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix https://github.com/mipops/dvrescue/issues/94.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1416

### CODE REVIEW

**Comment by dericed** [comment]
@JeromeMartinez  Please address conflict. Also, do you have a build of this for testing?

**Comment by dericed** [comment]
Closes https://github.com/mipops/dvrescue/issues/94

**Comment by dericed** [comment]
I merged this one too quick. I noticed that it works with rdt_nc, but I can't create an output with `@tc_nc='2'`.

mix.dv should cause this at frame 59 but doesn't: `% dvrescue samples/mix.dv `
```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.2">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20211017</version>
		<library version="21.09">MediaInfoLib</library>
	</creator>
	<media ref="samples/mix.dv" format="DV" size="64320000">
		<frames count="59" pts="00:00:00.000000" end_pts="00:00:01.968633" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="16/9" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" tc="02:00:00:00" rdt="1970-01-01 00:00:00" seqn="6"/>
			<frame n="58" pos="6960000" pts="00:00:01.935266" tc="02:00:01:28" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="59" pts="00:00:01.968633" end_pts="00:00:03.937266" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="59" pos="7080000" pts="00:00:01.968633" tc="01:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="117" pos="14040000" pts="00:00:03.903900" tc="01:00:01:28" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="50" pts="00:00:03.937266" end_pts="00:00:05.937266" size="720x576" video_rate="25" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="32000" channels="2">
			<frame n="118" pos="14160000" pts="00:00:03.937266" tc="04:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="167" pos="21216000" pts="00:00:05.897266" tc="04:00:01:24" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="50" pts="00:00:05.937266" end_pts="00:00:07.937266" size="720x576" video_rate="25" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="168" pos="21360000" pts="00:00:05.937266" tc="03:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="217" pos="28416000" pts="00:00:07.897266" tc="03:00:01:24" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="50" pts="00:00:07.937266" end_pts="00:00:09.937266" size="720x576" video_rate="25" chroma_subsampling="4:2:0" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="218" pos="28560000" pts="00:00:07.937266" tc="05:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="267" pos="35616000" pts="00:00:09.897266" tc="05:00:01:24" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="59" pts="00:00:09.937266" end_pts="00:00:11.905900" size="720x480" video_rate="30000/1001" chroma_subsampling="4:2:2" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="268" pos="35760000" pts="00:00:09.937266" tc="06:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="326" pos="49680000" pts="00:00:11.872533" tc="06:00:01:28" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
		<frames count="50" pts="00:00:11.905900" end_pts="00:00:13.905900" size="720x576" video_rate="25" chroma_subsampling="4:2:2" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="327" pos="49920000" pts="00:00:11.905900" tc="07:00:00:00" tc_nc="1" rdt="1970-01-01 00:00:00" rdt_nc="2" seqn="6" seqn_r="1"/>
			<frame n="376" pos="64032000" pts="00:00:13.865900" tc="07:00:01:24" rdt="1970-01-01 00:00:01" seqn="6" seqn_r="1"/>
		</frames>
	</media>
</dvrescue>
```

**Comment by dericed** [comment]
Also, I noticed that going from null value to value gives `@rdt_nc='2'`. I prefer 1, as null seems more equivalent to zero than infinity.

```
			<frame n="5" pos="600000" pts="00:00:00.166833" abst="80" tc="00:00:00;08" tc_nc="1" seqn="F"/>
			<frame n="6" pos="720000" pts="00:00:00.200200" abst="100" tc="00:00:00;10" tc_nc="1" seqn="F"/>
			<frame n="1162" pos="139440000" pts="00:00:38.772066" abst="11660" tc="00:00:38;26" rdt="2001-07-14 14:29:16" rdt_nc="2" seqn="F"/>
			<frame n="1230" pos="147600000" pts="00:00:41.041000" abst="12340" tc="00:00:41;04" rdt="2000-00-00 00:00:00;00" rdt_nc="2" seqn="F"/>
			<frame n="1243" pos="149160000" pts="00:00:41.474766" abst="12470" tc="00:00:41;17" rdt="2000-00-00 32:00:00;00" rdt_nc="1" seqn="F"/>
			<frame n="1251" pos="150120000" pts="00:00:41.741700" abst="12550" tc="00:00:41;25" rdt="2000-00-00 00:00:00;00" rdt_nc="2" seqn="F"/>
```

**Comment by dericed** [comment]
Shall we include the same logic for `@seq_nc`?

**Comment by JeromeMartinez** [comment]
> Also, I noticed that going from null value to value gives @rdt_nc='2'. I prefer 1, as null seems more equivalent to zero than infinity.

I guess that there is a date/time value in frame 1161 in your example, test is done only if there is a value.
AFAIK there is no error raised when date/time goes from null to a value, and no `@rdt_nc`.

**Comment by JeromeMartinez** [comment]
> Shall we include the same logic for @seq_nc?

Implemented in next PR, but not sure it is relevant because a jump from 14 to 0 is considered in past but could be a jump in future (14+2 = 16 so 0).
Maybe some tweaking in next version...

**Pull request merged**
