### PR TITLE
Add partial capture info to xml

### LINKED ISSUE #659: add xml attribute for partial xml creation
As discussed at https://github.com/mipops/dvrescue/pull/650#issuecomment-1329482080

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #659 

Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
It includes timeoout check for deck capture. Possible to have 2 separate PRs?

**Review by JeromeMartinez — APPROVED** [review]
Tested with simulator and I have well `<stop method='user' extra='SIGINT'/>`

**Comment by g-maxime** [comment]
> It includes timeoout check for deck capture. Possible to have 2 separate PRs?

Timeout check is already merged (#658), this PR only adds timeout reporting into the XML.

**Comment by dericed** [comment]
This needs an XSD update too at https://github.com/mipops/dvrescue/blob/main/tools/dvrescue.xsd

**Pull request merged**
