### PR TITLE
[WIP] Fix crash in case of big jumps in time codes

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix https://github.com/mipops/dvrescue/issues/212.

### CODE REVIEW

**Comment by dericed** [comment]
have a build?

**Comment by JeromeMartinez** [comment]
[snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/20221010/dvrescue_CLI_0.21.11.20221010_Mac.dmg).

**Comment by dericed** [comment]
blerg, conflicts now. Tested and will merge when conflict is resolved.

**Comment by JeromeMartinez** [comment]
It also has a regression with some corner cases (merge when some of inputs have frames without abst/timecode, frames are incorrectly merged with the frames of the input having frames with abst/timecode), working on it (so the WIP added :) ).

**Comment by dericed** [comment]
@JeromeMartinez, noting this pr now has conflicts.

**Comment by dericed** [comment]
closing in favor of https://github.com/mipops/dvrescue/pull/742

**Pull request closed without merging**
