### PR TITLE
Dvloupe interface

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by dericed** [comment]
@libbyhopfauf can you add an svg as a button to the loupe interface

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf can you add an svg as a button to the loupe interface

sure! let me know any specifics you were thinking of for the layout and I can do some mock-ups this week!

**Comment by dericed** [comment]
@libbyhopfauf here is what the button looks like now (just an 'o') 

image

**Comment by dericed** [comment]
@ElderOrb, can you show the image bigger, default to native frame size, or make resizeable.

Also can you make it so when you select a row of hex (where the row starts with a '9'), then add the `-B` option. For example, if you're running `dvplay -O - -b 0 file.dv` and the user selects rows 18, 19 and 20 then run `dvplay -B 17,18,19 -O - -b 0 file.dv`. That should make a little highlight block on those corresponding video dif blocks.

**Comment by dericed** [comment]
Also could you display the tooltip somehow, currently the gui doesn't show it.

**Comment by dericed** [comment]
Hi @ElderOrb, to get this unstuck could you skip the button to open this view and instead make the frame number in that column look like a clickable hyperlink that opens the loupe viewer.

**Comment by libbyhopfauf** [comment]
> @libbyhopfauf here is what the button looks like now (just an 'o')
> 
> image

Sure! I'll get some mock-ups together this afternoon. Just to clarify, we just need a dvloupe icon for the button, yeah? Or was there more of a design revision than that?

**Comment by libbyhopfauf** [comment]
Mock-ups for the icon on the button to open the dvloupe interface:


dvloupe_icon_example-05
dvloupe_icon_example-06
dvloupe_icon_example-07

**Pull request merged**
