### PR TITLE
[WIP] Do not output synthetic gray/silence frames at begin/end

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix https://github.com/mipops/dvrescue/issues/603.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1606.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
[Snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/20221014/).

With option for same as before:

```
> dvrescue device://0 -m a.dv -v 9 --csv --merge-output-nodata
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,31380,,,00:01:44;20,,,,,,,,0,,,0,0,0,0.0,32,0,0
47,31850,,1,00:01:46;07,,1,2005-11-05 13:14:38,,,,,0,,,0,0,0,0.0,31,120000,120000
554,36920,,1,00:02:03;06,,1,2005-11-05 13:14:55,,1,,,0,,,0,0,0,0.0,31,240000,240000
558,36960,,1,00:02:03;10,,1,,,,,,0,,,0,0,0,0.0,32,360000,360000
```

by default:
```
> dvrescue device://0 -m a.dv -v 9 --csv --merge-output-nodata
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
47,31850,,1,00:01:46;07,,1,2005-11-05 13:14:38,,,,,0,,,0,0,0,0.0,31,120000,0
554,36920,,1,00:02:03;06,,1,2005-11-05 13:14:55,,1,,,0,,,0,0,0,0.0,31,240000,120000
```

Note that `FramePos` always includes discarded frames and missing frames (from time code discontinuity), if it should change it would be for a separate, more general PR.

**Comment by dericed** [comment]
Currently this isn't ignoring the gray frames at the end? I'm attaching a complete capture with the 20221014 build.

[grey-at-end.dv.dvrescue.xml.zip](https://github.com/mipops/dvrescue/files/9796060/grey-at-end.dv.dvrescue.xml.zip)
[grey-at-end.dv.zip](https://github.com/mipops/dvrescue/files/9796061/grey-at-end.dv.zip)

Also here's a sample from @iamdamosuzuki which has the same issue (not sure if it's from an HVR-M15u or recorded into the tape). 
[Unknown_DV_Audio_Error_first20.dv.zip](https://github.com/mipops/dvrescue/files/9796075/Unknown_DV_Audio_Error_first20.dv.zip)

**Comment by dericed** [comment]
Hey @JeromeMartinez, am testing this again as it stalls the https://github.com/mipops/dvrescue/pull/595 pr.

When the deck is stopped and I run `$ dvrescue device://0 -m a2.dv -v 9 --csv --merge-output-nodata` the command terminates around the same time as the deck moving into play mode.

Thus I add `--timeout 10` so that the command doesn't time out while skipping the grey frames at the beginning when the tape is moving into position. What is the default that you use for timeout? Can you increase it slightly to allow for the tape to move into play mode and document the default in the command line help.

```
$ dvrescue device://0 -m a5.dv -v 9 --csv --merge-output-nodata --timeout 10
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,381080,,,00:21:11;16,,,,,,,,0,,,0,0,0,1.0,32,0,0
1,381080,1,,00:21:11;16,1,,,,,,,0,,,0,0,0,1.0,32,120000,120000
2,381080,1,,00:21:11;16,1,,,,,,,0,,,0,0,0,1.0,32,240000,240000
2022-11-18 16:55:08.821 dvrescue[24264:261778] Frame dropped.
48,381540,,1,00:21:13;02,,1,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,360000,360000
49,381550,,,00:21:13;03,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,480000,480000
50,381560,,,00:21:13;04,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,600000,600000
51,381570,,,00:21:13;05,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,720000,720000
52,381580,,,00:21:13;06,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,840000,840000
53,381590,,,00:21:13;07,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,960000,960000
54,381600,,,00:21:13;08,,,2005-11-05 13:34:05,,,,,0,,,0,0,0,1.0,31,1080000,1080000
55,381610,,,00:21:13;09,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1200000,1200000
56,381620,,,00:21:13;10,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1320000,1320000
57,381630,,,00:21:13;11,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1440000,1440000
58,381640,,,00:21:13;12,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1560000,1560000
59,381650,,,00:21:13;13,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1680000,1680000
60,381660,,,00:21:13;14,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1800000,1800000
61,381670,,,00:21:13;15,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,1920000,1920000
62,381680,,,00:21:13;16,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2040000,2040000
63,381690,,,00:21:13;17,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2160000,2160000
64,381700,,,00:21:13;18,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2280000,2280000
65,381710,,,00:21:13;19,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2400000,2400000
66,381720,,,00:21:13;20,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2520000,2520000
67,381730,,,00:21:13;21,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2640000,2640000
68,381740,,,00:21:13;22,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2760000,2760000
69,381750,,,00:21:13;23,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,2880000,2880000
70,381760,,,00:21:13;24,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3000000,3000000
71,381770,,,00:21:13;25,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3120000,3120000
72,381780,,,00:21:13;26,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3240000,3240000
73,381790,,,00:21:13;27,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3360000,3360000
74,381800,,,00:21:13;28,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3480000,3480000
75,381810,,,00:21:13;29,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3600000,3600000
76,381820,,,00:21:14;00,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3720000,3720000
77,381830,,,00:21:14;01,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3840000,3840000
78,381840,,,00:21:14;02,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,3960000,3960000
79,381850,,,00:21:14;03,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4080000,4080000
80,381860,,,00:21:14;04,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4200000,4200000
81,381870,,,00:21:14;05,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4320000,4320000
82,381880,,,00:21:14;06,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4440000,4440000
83,381890,,,00:21:14;07,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4560000,4560000
84,381900,,,00:21:14;08,,,2005-11-05 13:34:06,,,,,0,,,0,0,0,1.0,31,4680000,4680000
85,381910,,,00:21:14;09,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,4800000,4800000
86,381920,,,00:21:14;10,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,4920000,4920000
87,381930,,,00:21:14;11,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5040000,5040000
88,381940,,,00:21:14;12,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5160000,5160000
89,381950,,,00:21:14;13,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5280000,5280000
90,381960,,,00:21:14;14,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5400000,5400000
91,381970,,,00:21:14;15,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5520000,5520000
92,381980,,,00:21:14;16,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5640000,5640000
93,381990,,,00:21:14;17,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5760000,5760000
94,382000,,,00:21:14;18,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,5880000,5880000
95,382010,,,00:21:14;19,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,6000000,6000000
96,382020,,,00:21:14;20,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,6120000,6120000
97,382030,,,00:21:14;21,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,6240000,6240000
98,382040,,,00:21:14;22,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,6360000,6360000
99,382050,,,00:21:14;23,,,2005-11-05 13:34:07,,,,,0,,,0,0,0,1.0,31,6480000,6480000
2022-11-18 16:55:13.209 dvrescue[24264:261778] Frame dropped.
103,382090,,1,00:21:14;27,,1,,,,,,0,,,0,0,0,1.0,32,6600000,6600000
104,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,6720000,6720000
105,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,6840000,6840000
106,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,6960000,6960000
107,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7080000,7080000
108,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7200000,7200000
109,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7320000,7320000
110,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7440000,7440000
111,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7560000,7560000
112,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7680000,7680000
113,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7800000,7800000
114,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,7920000,7920000
115,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8040000,8040000
116,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8160000,8160000
117,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8280000,8280000
118,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8400000,8400000
119,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8520000,8520000
120,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8640000,8640000
121,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8760000,8760000
122,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,8880000,8880000
123,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9000000,9000000
124,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9120000,9120000
125,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9240000,9240000
126,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9360000,9360000
127,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9480000,9480000
128,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9600000,9600000
129,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9720000,9720000
130,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9840000,9840000
131,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,9960000,9960000
132,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10080000,10080000
133,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10200000,10200000
134,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10320000,10320000
135,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10440000,10440000
136,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10560000,10560000
137,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10680000,10680000
138,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10800000,10800000
139,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,10920000,10920000
140,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,11040000,11040000
141,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,11160000,11160000
142,382090,1,,00:21:14;27,1,,,,,,,0,,,0,0,0,1.0,32,11280000,11280000
$
```
however in this output there are gray frames at the beginning and the end.
[a5.dv.zip](https://github.com/mipops/dvrescue/files/10045098/a5.dv.zip)

You mentioned `--merge-output-nodata` but is this from an earlier draft as I can't find that command.

When I test again `--merge-ignore-concealed` I get an output file where there aren't gray frames in the beginning (for a tape capture starting in stop position) but there are lots of the usual grey frames at the end. Can this option ignore ending concealed gray frames too?

```
$ dvrescue device://0 -m a7.dv -v 9 --csv --merge-ignore-concealed
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
2022-11-18 17:00:13.549 dvrescue[24841:267755] Frame dropped.
48,385640,,1,00:21:26;22,,1,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,360000,0
49,385650,,,00:21:26;23,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,480000,120000
50,385660,,,00:21:26;24,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,600000,240000
51,385670,,,00:21:26;25,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,720000,360000
52,385680,,,00:21:26;26,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,840000,480000
53,385690,,,00:21:26;27,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,960000,600000
54,385700,,,00:21:26;28,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1080000,720000
55,385710,,,00:21:26;29,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1200000,840000
56,385720,,,00:21:27;00,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1320000,960000
57,385730,,,00:21:27;01,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1440000,1080000
58,385740,,,00:21:27;02,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1560000,1200000
59,385750,,,00:21:27;03,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1680000,1320000
60,385760,,,00:21:27;04,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1800000,1440000
61,385770,,,00:21:27;05,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,1920000,1560000
62,385780,,,00:21:27;06,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,2040000,1680000
63,385790,,,00:21:27;07,,,2005-11-05 13:34:19,,,,,0,,,0,0,0,1.0,31,2160000,1800000
2022-11-18 17:00:16.754 dvrescue[24841:267755] Frame dropped.
91,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5160000,1920000
92,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5280000,2040000
93,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5400000,2160000
94,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5520000,2280000
95,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5640000,2400000
96,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5760000,2520000
97,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,5880000,2640000
98,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6000000,2760000
99,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6120000,2880000
100,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6240000,3000000
101,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6360000,3120000
102,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6480000,3240000
103,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6600000,3360000
104,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6720000,3480000
105,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6840000,3600000
106,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,6960000,3720000
107,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7080000,3840000
108,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7200000,3960000
109,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7320000,4080000
110,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7440000,4200000
111,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7560000,4320000
112,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7680000,4440000
113,385830,1,,00:21:27;11,1,,,,,,,0,,,0,0,0,1.0,32,7800000,4560000
```

[a7.dv.zip](https://github.com/mipops/dvrescue/files/10045116/a7.dv.zip)

**Comment by JeromeMartinez** [comment]
I have made a mistake with the command line, use ` --merge-ignore-nodata` for ignoring gray frames.
With [grey_data_grey.zip](https://github.com/mipops/dvrescue/files/10123934/grey_data_grey.zip):

```
grey_data_grey.dv -y -m a.dv -v 9 --csv --merge-output-nodata
[...]
0,31380,,,00:01:44;20,,,,,,,,0,,,0,0,0,0.0,32,0,0
47,31850,,1,00:01:46;07,,1,2005-11-05 13:14:38,,,,,0,,,0,0,0,0.0,31,120000,120000
554,36920,,1,00:02:03;06,,1,2005-11-05 13:14:55,,1,,,0,,,0,0,0,0.0,31,240000,240000
558,36960,,1,00:02:03;10,,1,,,,,,0,,,0,0,0,0.0,32,360000,360000
```

```
grey_data_grey.dv -y -m a.dv -v 9 --csv --merge-ignore-nodata
[...]
47,31850,,1,00:01:46;07,,1,2005-11-05 13:14:38,,,,,0,,,0,0,0,0.0,31,120000,120000
554,36920,,1,00:02:03;06,,1,2005-11-05 13:14:55,,1,,,0,,,0,0,0,0.0,31,240000,240000
```

> Currently this isn't ignoring the gray frames at the end?

content at the end of grey-at-end.dv is not considered as "nodata" because audio content is between -6 and 2, and I exclude if only between -2 and 1, should I expand the test to e.g. -8 to 8?

> When I test again --merge-ignore-concealed I get an output file where there aren't gray frames in the beginning (for a tape capture starting in stop position) but there are lots of the usual grey frames at the end. Can this option ignore ending concealed gray frames too?

concealed and gray are with different option, so ` --merge-ignore-concealed --merge-ignore-nodata`, IMO they should be independent.

> [a5.dv.zip](https://github.com/mipops/dvrescue/files/10045098/a5.dv.zip)

With ` --merge-ignore-nodata` output has more gray frames, but report is weird (1 frame at the beginning "removed" in the report but 3, as expected, actually removed), investigating but not blocking.

**Comment by dericed** [comment]
@JeromeMartinez, can you rebase on main and send a new snapshot?

**Comment by JeromeMartinez** [comment]
https://mediaarea.net/download/snapshots/binary/dvrescue/20231020/dvrescue_CLI_0.21.11.20231020_Mac.dmg

**Pull request merged**
