### PR TITLE
DeckLink Input: Add frame saturation statistics

### LINKED ISSUE #857: add signalstats values to decklink capture xml and csv
based off https://github.com/mipops/dvrescue/issues/767.

I'd like a few signalstats values in the xml, such as
```xml
<frame n="0" pos="0" pts="00:00:00.000000" tc="01:16:11:01" seqn="F">
   <signalstats satmax="900"/>
</frame>
```

Note that we'd need to add bitdepth to the `<frames>` element and to the csv output to contextualize the satmax value.

I'm open minded if these new filter values are as attributes or sub-elements.

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #857

- For 8/10 bit YUV
- Tested only with the simulator; Please test with a DeckLink device.
- Bitdepth can be deduced from the pixel_format attribute, but I can also add a bitdepth attribute if needed.

Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20240606-2

Sample output:
```
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.2.1">
	<creator>
		<program>dvrescue</program>
		<version>22.12</version>
		<library version="24.05.20240601">MediaInfoLib</library>
	</creator>
	<media>
		<source video="sdi" audio="embedded" timecode="vitc"/>
		<frames count="300" pts="00:00:00.000000" end_pts="00:00:10.010000" size="720x486" pixel_format="uyvy" video_rate="30000/1001" audio_rate="48000" channels="2">
			<frame n="0" pts="00:00:00.000000">
				<signalstats satavg="113.63" sathi="119" satmax="135"/>
			</frame>
                        ...
			<frame n="299" pts="00:00:09.976633">
				<signalstats satavg="113.452" sathi="119" satmax="136"/>
			</frame>
		</frames>
	</media>
</dvrescue>
```

### CODE REVIEW

**Comment by dericed** [comment]
Will test soon. Does this have the saturation values in the csv output as well?

**Comment by g-maxime** [comment]
> Will test soon. Does this have the saturation values in the csv output as well?

Oops, I forgot.
Next snapshot

**Comment by dericed** [comment]
Do any snapshots have this PR with the latest --csv commit? I tried the one that you linked and the 0609 build and just see:

```
$ dvrescue device://84:160a010c:00000000 --control "/dev/tty.RS422 Deck Control" -m test2.mkv -x test2.xml --csv
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,,,,00:01:10;27,,,,,,,,,,,,,,,,,
1,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
2,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
3,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
4,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
5,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
6,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
7,,,,00:01:10;27,1,,,,,,,,,,,,,,,,
```

**Comment by g-maxime** [comment]
With the [0606-3](https://mediaarea.net/download/snapshots/binary/dvrescue/20240606-3) snapshot and the simulator:
```
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,pix_fmt,satavg,sathi,satmax,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,,,,XX:XX:XX:XX,,,,,,,,,v210,455.525,478,543,,,,,,,,,
1,,,,XX:XX:XX:XX,,,,,,,,,v210,454.958,478,540,,,,,,,,,
2,,,,XX:XX:XX:XX,,,,,,,,,v210,454.381,478,543,,,,,,,,,
...
```

Is the XML output working?

**Comment by dericed** [comment]
Could you change name of value from sathi to sathigh to match the value names of the [signalstats filter](https://ffmpeg.org/ffmpeg-filters.html#signalstats-1). Otherwise looks good, thanks for adding the xsd update.

**Pull request merged**
