### PR TITLE
Add macOS permissions for USB-Serial and DeckLink devices

### LINKED ISSUE #841: bundles dvrescue cli in gui doesn't support decklink input
Using CLI within GUI from 24.03 release no decklink device is seen:
```
drice:~ drice$ /Applications/dvrescue.app/Contents/Helpers/dvrescue --version
DVRescue v.24.03 (MediaInfoLib v.24.01) by MIPoPS.

drice:~ drice$ /Applications/dvrescue.app/Contents/Helpers/dvrescue -list_devices_json
2024-03-29 15:34:15.228 dvrescue[24057:7279005] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
[]
```

But dvrescue from the 20240318 daily build and the 24.03 daily build do see the decklink device:
```
drice:~ drice$ dvrescue --version
DVRescue v.22.12.20240318 (MediaInfoLib v.24.01) by MIPoPS.
drice:~ drice$ dvrescue -list_devices_json
2024-03-29 15:34:24.584 dvrescue[24067:7279168] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
[{"id":"84:160a010c:00000000","name":"UltraStudio HD Mini","type":"DeckLink"}]


drice:~ drice$ dvrescue --version
DVRescue v.24.03 (MediaInfoLib v.24.01) by MIPoPS.
drice:~ drice$ dvrescue -list_devices_json
2024-03-29 15:36:17.843 dvrescue[24465:7282776] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
[{"id":"84:160a010c:00000000","name":"UltraStudio HD Mini","type":"DeckLink"}]
```

Something missing in the bundled dvrescue cli for the gui?

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #841

Untested, please test **from GUI**

[Snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240609)

### CODE REVIEW

**Comment by dericed** [comment]
hmm, not working for me.

I installed the gui and cli from that date:

```
$ dvrescue --list_devices
84:160a010c:00000000: UltraStudio HD Mini [DeckLink]

$ /Applications/dvrescue.app/Contents/MacOS/dvrescue --log
appDirPath:  "/Applications/dvrescue.app/Contents/MacOS"
enable file logging...
Checking for log folder existence: /Users/drice/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs
existing log QFileInfo(/Users/drice/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs/dvrescue-gui.log) has been removed
[2024:06:10 15:40:40 -04:00] [warning] [thread 25865462] [qt.qpa.fonts] Populating font family aliases took 147 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PackagePage.qml:338:25: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PackageFileView.qml:85:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PackageFileView.qml:59:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/MergeFileView.qml:87:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/MergeFileView.qml:61:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalysePage.qml:622:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalyseFileView.qml:84:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalyseFileView.qml:58:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalysePage.qml:263:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalysePage.qml:256:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PlotsView.qml:389:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PlotsView.qml:80:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/AnalysePage.qml:242:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] qrc:/PlayerView.qml:184:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] Both point size and pixel size set. Using pixel size.
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] Both point size and pixel size set. Using pixel size.
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] Both point size and pixel size set. Using pixel size.
[2024:06:10 15:40:43 -04:00] [warning] [thread 25865053] Both point size and pixel size set. Using pixel size.
2024-06-10 15:40:43.860 dvrescue[65645:25865053] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

log from gui
https://gist.github.com/dericed/cc523714f052ac8a5a9c80efa638bf94

**Comment by dericed** [comment]
Snapshot after latest commit?

**Comment by g-maxime** [comment]
> Snapshot after latest commit?

https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240611-2/

**Comment by dericed** [comment]
@g-maxime unfortunately still not there, https://gist.github.com/dericed/d330257c357293d62e8f946540ff33cb.

```
$ dvrescue --version
DVRescue v.22.12.20240611 (MediaInfoLib v.24.05) by MIPoPS.
drice:BlueSCSI-v2 drice$ dvrescue --list_devices
84:160a010c:00000000: UltraStudio HD Mini [DeckLink]
drice:BlueSCSI-v2 drice$ /Applications/dvrescue.app/Contents/MacOS/dvrescue --log
appDirPath:  "/Applications/dvrescue.app/Contents/MacOS"
enable file logging...
Checking for log folder existence: /Users/drice/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs
existing log QFileInfo(/Users/drice/Library/Containers/net.MediaArea.dvrescue.mac-gui/Data/dvrescue-gui_logs/dvrescue-gui.log) has been removed
[2024:06:13 21:59:21 -04:00] [warning] [thread 14364] [qt.qpa.fonts] Populating font family aliases took 206 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PackagePage.qml:338:25: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PackageFileView.qml:85:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PackageFileView.qml:59:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/MergeFileView.qml:87:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/MergeFileView.qml:61:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalysePage.qml:622:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalyseFileView.qml:84:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalyseFileView.qml:58:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalysePage.qml:263:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalysePage.qml:256:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PlotsView.qml:389:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PlotsView.qml:80:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/AnalysePage.qml:242:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] qrc:/PlayerView.qml:184:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] Both point size and pixel size set. Using pixel size.
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] Both point size and pixel size set. Using pixel size.
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] Both point size and pixel size set. Using pixel size.
[2024:06:13 21:59:24 -04:00] [warning] [thread 12404] Both point size and pixel size set. Using pixel size.
2024-06-13 21:59:25.333 dvrescue[1393:12404] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

Shall I set up remote access to a test station?

**Comment by g-maxime** [comment]
With[ latest version](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240617-5/dvrescue_GUI_22.12.20240617_Mac.dmg) DeckLink detection and playing works.

Serial control is still not working.

**Comment by JeromeMartinez** [comment]
Warning, [doc](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation) says "Because library validation is such an important security-hardening feature, Gatekeeper runs extra security checks on programs that have it disabled." so I guess that this is a good "hotfix" but I bet that at some point Apple will forbid that.

**Comment by dericed** [comment]
@JeromeMartinez see page 12 on https://documents.blackmagicdesign.com/UserManuals/DesktopVideoManual.pdf. Blackmagic already requires `reduced security` policy with their hardware. Related?

**Comment by JeromeMartinez** [comment]
> Related?

I guess so.

**Comment by JeromeMartinez** [comment]
> Blackmagic already requires reduced security policy with their hardware.

But "From Desktop Video 12.2 or later, it is no longer necessary to have ‘reduced security’ enabled", so maybe we'll be able to configure it without that, but @g-maxime succeeds to have the GUI working with ‘reduced security’ enabled is already a good first step and we see later for a better solution.

**Comment by dericed** [comment]
@g-maxime, any hope on this one? I tested with https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240617-5/dvrescue_GUI_22.12.20240617_Mac.dmg and saw that it recognized my decklink device.

**Comment by g-maxime** [comment]
Please test https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240717-2/dvrescue_GUI_22.12.20240717_Mac.dmg

With the 'Native' control interface.

**Comment by dericed** [comment]
testing now. When I have a decklink card connected, the capture interface recognized the deck. With Native interface, when I connect the commander cable then no result, but with decklink rs422 then when select Native and press play then it sends the deck into fast forward.

**Pull request merged**
